export const getUsers=async(req,res)=>{
    try{

    }
    catch(error){
        console.log(error);
        res.status(500).json({message: "Failed to get users"})
    }
}

export const getUser=async(req,res)=>{
    try{

    }
    catch(error){
        console.log(error);
        res.status(500).json({message: "Failed to get users"})
    }
}

export const updateUser=async(req,res)=>{
    try{

    }
    catch(error){
        console.log(error);
        res.status(500).json({message: "Failed to get users"})
    }
}

export const dleteUser=async(req,res)=>{
    try{

    }
    catch(error){
        console.log(error);
        res.status(500).json({message: "Failed to get users"})
    }
}